const constants = {
    // CURRENT
    SET_LISTID: "SET_LISTID",
    SET_LIST: "SET_LIST",
    SET_TASKID: "SET_TASKID",
    SET_TASK: "SET_TASK",
    SET_STEPS: "SET_STEPS",

    // LIST
    ADD_LIST: "ADD_LIST",
    REMOVE_LIST: "REMOVE_LIST",
    RENAME_LIST: "RENAME_LIST",
    EDIT_TITLE: "EDIT_TITLE",
    SUBMIT_TITLE: "SUBMIT_TITLE",
    
    // TASK
    LOAD_TASKS: "LOAD_TASKS",
    ADD_TASK: "ADD_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    EDIT_TASK_STATUS_COMPLETE: "EDIT_TASK_STATUS_COMPLETE",
    EDIT_TASK_STATUS_IMPORTANT: "EDIT_TASK_STATUS_IMPORTANT",
    EDIT_TASK_STATUS_MYDAY: "EDIT_TASK_STATUS_MYDAY",
    UPDATE_TASK: "UPDATE_TASK",

    // SEARCH
    CHANGE_QUERY: "CHANGE_QUERY",
    CLEAR_QUERY: "CLEAR_QUERY",

    // SORTBAR
    SET_BGCOLOR: "SET_BGCOLOR",
    SET_ORDERBY: "SET_ORDERBY",
    SET_ORDERDIR: "SET_ORDERDIR",
    RESET_ORDERDIR: "RESET_ORDERDIR",
    TOGGLE_HIDE: "TOGGLE_HIDE",
    
    // SECTION - MORE
    OPEN_MORE: "OPEN_MORE",
    CLOSE_MORE: "CLOSE_MORE",
    ADD_STEP: "ADD_STEP",
    REMOVE_STEP: "REMOVE_STEP",
    EDIT_STEP_STATUS_COMPLETE: "EDIT_STEP_STATUS_COMPLETE",
    UPDATE_STEP: "UPDATE_STEP"
}

export default constants;