const constants = {
    SELECTED_LISTID: "SELECTED_LISTID",
    SELECTED_TASKID: "SELECTED_TASK_ID",
    LOAD_TASKS: "LOAD_TASKS",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK_STATUS_COMPLETE: "EDIT_TASK_STATUS_COMPLETE",
    EDIT_TASK_STATUS_IMPORTANT: "EDIT_TASK_STATUS_IMPORTANT",
    EDIT_TASK_STATUS_MYDAY: "EDIT_TASK_STATUS_MYDAY",
    REMOVE_TASK: "REMOVE_TASK",
    CHANGE_QUERY: "CHANGE_QUERY",
    CLEAR_QUERY: "CLEAR_QUERY",
    SET_ORDERBY: "SET_ORDERBY",
    SET_ORDERDIR: "SET_ORDERDIR",
    RESET_ORDERDIR: "RESET_ORDERDIR",
    TOGGLE_HIDE: "TOGGLE_HIDE",
    SET_BGCOLOR: "SET_BGCOLOR",
    ADD_LIST: "ADD_LIST",
    REMOVE_LIST: "REMOVE_LIST",
    RENAME_LIST: "RENAME_LIST",
    EDIT_TITLE: "EDIT_TITLE",
    SUBMIT_TITLE: "SUBMIT_TITLE",
    SET_PLACEHOLDER: "SET_PLACEHOLDER",
    
    // SECTION - MORE
    OPEN_MORE: "OPEN_MORE",
    CLOSE_MORE: "CLOSE_MORE"
}

export default constants;