const constants = {
    SET_TITLE: "SET_TITLE",
    SET_MOREINFO: "SET_MOREINFO",
    LOAD_TASKS: "LOAD_TASKS",
    ADD_TASK: "ADD_TASK",
    EDIT_TASK_STATUS_COMPLETE: "EDIT_TASK_STATUS_COMPLETE",
    EDIT_TASK_STATUS_IMPORTANT: "EDIT_TASK_STATUS_IMPORTANT",
    EDIT_TASK_STATUS_MYDAY: "EDIT_TASK_STATUS_MYDAY",
    REMOVE_TASK: "REMOVE_TASK",
    CHANGE_QUERY: "CHANGE_QUERY",
    CLEAR_QUERY: "CLEAR_QUERY",
    SET_ORDERBY: "SET_ORDERBY",
    SET_ORDERDIR: "SET_ORDERDIR",
}

export default constants;